### ISSUE TITLE
Password not being hashed on update `/User/:id`

### ISSUE THREAD

**Issue by siddhantprateek** [juicyllama/llana#40]
Hey, I'm using the test (demo) provided in the documentation https://juicyllama.com/tools/llana/demo. When updating the username and password via an API endpoint, the password is not being hashed during the update process. Consequently, when I attempt to log in with the updated credentials, the system compares the hashed password (from the login attempt) with the unhashed password stored in the database, causing a mismatch and preventing a successful login.

**Steps to Reproduce:**
1. Make a PUT request to `/User/:id` with the any payload to update the existing record (i.e.):
   ```json
   {
       "firstName": "Jake",
       "email": "sample@sample.com",
       "password": "random"
   }
   ```
2. The password gets stored in plain text rather than being hashed.
3. Attempt to log in with the updated credentials.
4. The login will fail due to the password mismatch (hashed vs. unhashed).

**Comment by andyslack** [comment]
Thanks for contributing, @siddhantprateek, and for the good explanation. I'm looking into this now.

**Comment by andyslack** [comment]
@siddhantprateek I'm pleased to report this has now been fixed.
